# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "test_util"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2021"
publish = false

[[bin]]
name = "test_server"
path = "src/test_server.rs"

[dependencies]
anyhow = "1.0.57"
async-stream = "0.3.3"
atty = "0.2.14"
base64 = "0.13.0"
flate2 = "1.0.24"
futures = "0.3.21"
hyper = { version = "0.14.18", features = ["server", "http1", "http2", "runtime"] }
lazy_static = "1.4.0"
once_cell = "1.10.0"
os_pipe = "1.0.1"
parking_lot = "0.12.0"
pretty_assertions = "=1.2.1"
regex = "1.6.0"
reqwest = { version = "0.11.11", default-features = false, features = ["rustls-tls", "stream", "gzip", "brotli", "socks"] }
ring = "0.16.20"
rustls-pemfile = "1.0.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tar = "0.4.38"
tokio = { version = "1.19", features = ["full"] }
tokio-rustls = "0.23"
tokio-tungstenite = "0.16"

[target.'cfg(unix)'.dependencies]
pty = "0.2.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["consoleapi", "handleapi", "namedpipeapi", "winbase", "winerror"] }
