name: Luwak main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]

    steps:
    # - uses: hecrj/setup-rust-action@v1
    #   with:
    #     rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
        rustup install ${{ matrix.rust }}
    - name: Run Build
      run: cargo -V;cargo build --release
