on:
  release:
    types: [created]

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest, macOS-latest]
        rust: [nightly]

    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain ${{ matrix.rust }}
        
    - name: Install protobuf compiler (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
      
    - name: Install protobuf compiler (macOS)
      if: matrix.os == 'macOS-latest'
      run: |
        brew install protobuf

    - name: Run Build
      run: |
        cargo build --release
        cp target/release/luwak target/release/luwak-${{ matrix.os }}
    - name: Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        files: target/release/luwak-${{ matrix.os }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}